### ISSUE TITLE
Improper Handling of Session Timeout 

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-admin-ui#107]
After my session timed out, I navigated back to the admin UI. It did not look logged out (some content was still displaying) like the profile page. But the links were not working. When I decided to logout, I was shown the following error:

![image](https://user-images.githubusercontent.com/3717101/116290878-f3ddd580-a761-11eb-8d21-bc826a06dd68.png)

We should always check to make sure the session is active. And you should never show an error like the above on a logout error.

**Comment by duttarnab** [comment]
Hi @yuriyz 

Need your advice here. I have checked https://gluu.org/docs/gluu-server/4.2/admin-guide/session/#session-timeouts. 

As per my understanding, RP (like admin-ui) should maintain their own session-timeout after which it should get automatically logout. So, `sessionIdLifetime` should be -1 so that it sets the OP session object to not have an expiration time.

If you think RP (like admin-ui) session-timeout should be  `sessionIdLifetime` then RP will need to update `lastUsedAt` at OP everytime there is some event on admin-ui.. which is a costly affair in terms of http request.

**Comment by yuriyz** [comment]
> As per my understanding, RP (like admin-ui) should maintain their own session-timeout after which it should get automatically logout. So, sessionIdLifetime should be -1 so that it sets the OP session object to not have an expiration time.

It depends on your goal but in general yes, it's valid scenario to maintain own RP session and put `-1` for OP session. However I would recommend `/end_session` once RP session is expired to force re-login. RP session lifetime is up to you.

**Comment by duttarnab** [comment]
Done, session timeout is maintained by RP. After session-timeout `/end_session` is called.
