### ISSUE TITLE
Delete feature in `All Attributes` screen is not working

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/gluu-admin-ui#53]
Delete feature in `All Attributes` screen is not working.

Note: Please only try to delete the attributes created by you. Deleation of existing attributes may stop the application. 
![image](https://user-images.githubusercontent.com/32794267/112331751-35044500-8cdf-11eb-8a5a-104d839d73b7.png)

**Comment by duttarnab** [comment]
Done

**Comment by dev-samiur** [comment]
Hello Arnab,

I am unable to message anyone on one to one chat on Rocket Chat(it keeps
loading). I kept trying from yesterday. In the attributes api, all the
individual attributes didn't include which field is mandatory and which is
not. Instead of that what I found is in every attribute there is one
property named requred(which has typo error) and which is false for all.

And inside the UI there are only two fields which are required. So made
only those two required or should i make based on attribute data

Thanks,
Samiur
